# -*- coding: utf-8 -*-
"""Spam Email Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AafkbTGVN4VTPwyrLnwKe2GwfBGqFuT7
"""

import numpy as np
import pandas as pd

data=pd.read_csv('spam_ham_dataset.csv')
data.head()

data.drop(['label',],axis=1,inplace=True)

data.head()

X=data.iloc[:,1]
y_data=data.iloc[:,-1]

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y_data)

c=CountVectorizer()
X_data=c.fit_transform(X_train.values)

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_data,y_train)

X_test_count=c.transform(X_test)
model.score(X_test_count,y_test)

email=input("Enter the Email that you want to check:--")
email_count=c.transform([email])
pred=model.predict(email_count)

if pred==1:
  print('The email is Spam')
else:
  print('The email is Ham')

